#!/usr/bin/env bash
# Fresh namespace only. Never overwrites an existing deployment or database.
source "$(dirname -- "$0")/lib-playground.sh"
require_context
for tool in age tar helm python3; do need "$tool"; done
: "${BACKUP_FILE:?Set BACKUP_FILE to the encrypted backup path}"
: "${AGE_IDENTITY:?Set AGE_IDENTITY to a private age identity file outside Git}"
: "${PREFLIGHT_REVIEWED:?Run and review preflight first}"
[[ "$PREFLIGHT_REVIEWED" == yes ]] || die "Preflight review required"
[[ "$(kubectl get namespace "$NAMESPACE" --ignore-not-found -o name)" == "" ]] || die "Restore requires a fresh namespace; existing namespace was not modified"
tmp="$(mktemp -d "$ROOT/_local/restore.XXXXXX")"
age -d -i "$AGE_IDENTITY" "$BACKUP_FILE" > "$tmp/backup.tar"
# Only the expected regular files may be restored from the outer archive.
python3 - "$tmp" <<'PY'
import pathlib, sys, tarfile
root=pathlib.Path(sys.argv[1])
allowed={"postgresql.dump","app-data.tar.gz","secret.json","values-session.yaml","Chart.yaml","Chart.lock","source-commit.txt"}
with tarfile.open(root/"backup.tar") as archive:
    for member in archive.getmembers():
        if member.isdir() and member.name in (".","./"): continue
        name=member.name.removeprefix("./")
        if name not in allowed | {"values-ingress.yaml"} or not member.isfile(): raise SystemExit("Unexpected backup archive member")
        with archive.extractfile(member) as src, (root/name).open("wb") as dst:
            import shutil
            shutil.copyfileobj(src,dst)
for name in allowed:
    if not (root/name).is_file(): raise SystemExit("Incomplete backup")
PY
cmp helm-chart/Chart.yaml "$tmp/Chart.yaml" || die "Restore using the same pinned chart first"
cmp helm-chart/Chart.lock "$tmp/Chart.lock" || die "Dependency lock differs"
# Copy old settings as a starting point; require already prepared new-session values.
[[ -f _local/values-session.yaml ]] || die "Prepare new-session values-session.yaml with current storage, model and HTTPS URL (see docs/recovery.md)"
build_dependencies
args=(-f helm-chart/values-playground.yaml -f _local/values-session.yaml)
[[ -z "${INGRESS_VALUES:-}" ]] || args+=(-f "$INGRESS_VALUES")
helm template "$RELEASE" helm-chart -n "$NAMESPACE" "${args[@]}" > _local/restore-rendered.yaml
python3 scripts/validate-config.py _local/restore-rendered.yaml --deployment
kubectl create namespace "$NAMESPACE"
python3 - "$tmp/secret.json" <<'PY'
import json, subprocess, sys
old=json.load(open(sys.argv[1]))
secret={"apiVersion":"v1","kind":"Secret","metadata":{"name":"openwebui-secrets","namespace":"thinkwithops-openwebui"},"type":"Opaque","data":old["data"]}
subprocess.run(["kubectl","create","-f","-"],input=json.dumps(secret),text=True,check=True,stdout=subprocess.DEVNULL)
PY
# Zero app replicas prevents migrations and writes before restoring.
helm upgrade --install "$RELEASE" helm-chart -n "$NAMESPACE" "${args[@]}" --set open-webui.replicaCount=0 --timeout 15m
# Do not Helm --wait yet: the app PVC uses WaitForFirstConsumer and has no pod.
k rollout status statefulset/openwebui-postgresql --timeout=15m
k rollout status deployment/openwebui-redis --timeout=5m
kubectl create -f scripts/maintenance-pod.yaml
k wait --for=condition=Ready pod/openwebui-maintenance --timeout=180s
# Refuse a populated PVC or database. No destructive --clean restore.
k exec pod/openwebui-maintenance -- python -c 'from pathlib import Path; assert not any(p.name != "lost+found" for p in Path("/data").iterdir()), "Application PVC is not empty"'
tables="$(k exec statefulset/openwebui-postgresql -- sh -ec 'PGPASSWORD="$POSTGRES_PASSWORD" psql -h 127.0.0.1 -U openwebui -d openwebui -Atc "SELECT count(*) FROM information_schema.tables WHERE table_schema = '\''public'\''"')"
[[ "$tables" == 0 ]] || die "Database is not empty; restore stopped"
k exec -i statefulset/openwebui-postgresql -- sh -ec 'PGPASSWORD="$POSTGRES_PASSWORD" pg_restore -h 127.0.0.1 -U openwebui -d openwebui --exit-on-error --no-owner --no-acl' < "$tmp/postgresql.dump"
# This archive is generated by backup.sh from the trusted application's PVC.
k exec -i pod/openwebui-maintenance -- tar -C /data -xzf - < "$tmp/app-data.tar.gz"
k delete pod openwebui-maintenance --wait=true --timeout=90s
helm upgrade "$RELEASE" helm-chart -n "$NAMESPACE" "${args[@]}" --wait --timeout 20m
rm -rf -- "$tmp"
echo 'Restore completed. Re-run verify.sh and browser history/upload checks; recovery is not proven until those pass.'
